---

- room_name: Sala 1
  title: cfp.level.basic
  schedule:
    - time:        "10:00 - 10:50"
      title:       Intro a BDD
      description: En esta charla se va a hacer una introducción a un proceso de desarrollo de aplicaciones basado en el comportamiento, sus diferencias con técnicas más conocidas como el TDD y como podemos utilizar herramientas como phpspec y Behat para automatizar nuestro tests.
      speaker:     iambrosi

- room_name: Sala 2
  title: cfp.level.intermediate
  schedule:
    - time:        "10:00 - 10:50"
      title:       introduction.title
      description: introduction.description
      speaker:     iambrosi

- room_name: Sala 3
  title: cfp.level.advanced
  schedule:
    - time:        "10:00 - 10:50"
      title:       introduction.title
      description: introduction.description
      speaker:     iambrosi
