talks:
    implementando-una-arquitectura-de-microservicios:
        title: 'Implementando una arquitectura de Microservicios'
        description: "La complejidad actual de los sistemas de software, la cantidad de distintas plataformas que se conectan a él, los equipos de desarrollo geodistribuidos, entre otros factores, hace que el paradigma de las aplicaciones monolíticas falle, necesitando uno nuevo mas flexible, especializado y ligero. La arquitectura de Microservicios brinda una visión y estrategia necesaria para implementar este nuevo paradigma. Veremos que características tiene esta arquitactura, ventajas y desventajas, como migrar de una plataforma monolítica a una basada en microservicios y algunas buenas prácticas para poder implementarla."
        speaker: federico
        level: cfp.level.intermediate

    html5-jquery-php:
        title: 'HTML5 + JQUERY + PHP'
        description: >
          En esta charla veremos como utilizar de manera eficiente la combinacion de estas 3 tecnologías, se analizaran diferentes casos típicos y debatiremos sobre cual es el uso específico de cada herramienta.
          Para finalizar la charla hablaremos sobre la importancia de la transferencia de datos, basándonos en las experiencias de usuarios y desarrollos ágiles.
        speaker: alanyusim
        level: cfp.level.intermediate

    como-disenar-apis-restful-sin-morir-en-el-intento:
        title: 'Cómo diseñar APIs RESTful sin morir en el intento.'
        description: "Vivimos en un mundo orientado a servicios interconectados. Las protagonistas de esta evolución: las APIs RESTful. Si tu aplicación está enfocada a servicios y al mundo entero tenés que saber cómo encararlas. Mostraré las mejores prácticas para diseñar APIs restful, desde su concepción hasta su ejecución, testing y documentación. Modelado de Entidades y colecciones, errores, estándares y mucho más. Con esta información estarás en condiciones de diseñar la API RESTful de tu próximo proyecto."
        speaker: av4tar
        level: cfp.level.basic

    introduccion-a-symfony-2:
        title: 'Introducción a Symfony 2'
        description: "Qué es Symfony? Qué puedes hacer con Symfony? Qué se necesita para utilizarlo? Cómo empezar? Principios básicos y recomendaciones. Se responderán todas estas preguntas y alguna otra más y se brindará un ejemplo básico."
        speaker: fabianv
        level: cfp.level.basic

    drupal-que-es-y-que-hay-de-nuevo-en-la-version-8:
        title: 'Drupal: Qué es? Y qué hay de nuevo en la versión 8…'
        description: "Esta charla consta de 2 partes. La primera orientada principalmente a estudiantes que nunca han utilizado un CMS, donde hablaré sobre cómo utilizamos Drupal en Percona y daré algunos consejos para empezar a crear sitios rápidamente. La segunda parte es para aquellos que ya han usado Drupal. Aquí hablaré sobre las nuevas características del (ahora sí) modernizado Drupal 8, tales como las mejoras en el panel de administración; la nueva forma de hacer Themes con Twig; el nuevo sistema de configuración; cambios en la API; y alguna otra novedad si me alcanza el tiempo."
        speaker: mauricios
        level: cfp.level.basic

    introduction-to-mongodb:
        title: 'Introduction to MongoDB'
        description: "Rápida introducción a la base de datos NoSql #1. Introduciré conceptos de NoSql, terminología y analogías con SQL para ayudarte a entender el mundo de las bases de datos documentales."
        speaker: markus
        level: null

    deployando-con-rocketeer:
        title: 'Deployando con Rocketeer'
        description: "Matías nos va a contar cómo deploya aplicaciones usando Rocketeer. Rocketeer es un sistema de deployment hecho en PHP. "
        speaker: matiasf
        level: cfp.level.intermediate

    intro-a-bdd:
        title: 'Intro a BDD'
        description: "En esta charla se va a hacer una introducción a un proceso de desarrollo de aplicaciones basado en el comportamiento, sus diferencias con técnicas más conocidas como el TDD y como podemos utilizar herramientas como phpspec y Behat para automatizar nuestro tests."
        speaker: iambrosi
        level: cfp.level.intermediate

    docker-from-the-basics-to-orquestration:
        title: 'Docker from the basics to orquestration'
        description: "Docker is an open platform for developers and sysadmins to build, distribute and execute applications. With docker you can standardise eliminating friction between development, homologation and production environments. Nevermore hear the sentence: \"But in my machine it is working!\". We will explain quickly how Docker does it's magic; The advantages over tradicional virtualization; We will also cover since the basics steps to create, edit and publish containers until a orchestration of multi containers like frontend, backend, workers and data persistence systems for example."
        speaker: wellington
        level: cfp.level.intermediate

    laravel-en-plan-ceibal:
        title: 'Laravel en Plan Ceibal'
        description: "La charla trata sobre cómo utilizó Plan Ceibal el Framework Laravel para desarrollar un Sistema de Administración de usuarios de todo el sistema educativo uruguayo. Abordaremos: introducción a Laravel, beneficios de usar este Framework, buenas prácticas, sincronización de base de datos con migrations, manejo de API, puestas en producción; todo desde la óptica de un caso real. Un Sistema que aloja cerca de 1: de usuarios."
        speaker: mmiglionico
        level: cfp.level.intermediate

    yii-inicios:
        title: 'Yii inicios'
        description: "La idea que tenia en mente es exponer las virtudes de utilizar Yii como framework en sus aplicaciones web Rest. Demostrar que Yii es una herramienta rápida y robusta a la hora de crear un aplicación sin tener la necesidad de saber en detalle la programación de PHP puro. Realizar una introducción de Yii, qué es y cuáles son sus ventajas. Brindar un enfoque técnico a través de una app simple, con  la creación de un CRUD. Explicar el proceso desde que me siento en la pc, hasta la instalación de xampp(windows) o lampp(ubuntu), y mencionar la facilidad que tiene crear un entorno de desarrollo con xampp el cual incluye mysql, apache y php. A través de phpmyadmin creamos la base de datos con una tabla, seguido de la instalación de yii, mencionando las configuraciones más relevantes, la estructura de directorios y archivos más importantes. Luego utilizamos la herramienta que incluye Yii, llamada Gii, que se encarga de generar el código de los modelos y del CRUD. Posteriormente se explica el código generado a través del patrón MVC. Para finalizar una ronda de preguntas."
        speaker: federicor
        level: cfp.level.basic

    php-endemoniado-una-plataforma-de-mensajeria-sobre-php-y-mysql:
        title: 'PHP endemoniado, una plataforma de mensajería sobre PHP y MySQL.'
        description: 'Un caso de uso de PHP fuera de la WEB. La evolución de una aplicación web de SMS a una plataforma integral de mensajería y las transformaciones culturales y tecnológicas necesarias para lograrlo. Cuales fueron los problemas de performance y escalabilidad y las soluciones que encontramos. Finalmente, alternativas de implementación, basadas en las tecnologías disponibles.'
        speaker: [marcelob, ivan]
        level: null

    intro-a-d3-para-los-mas-chambones:
        title: 'Intro a D3 para los más chambones.'
        description: "Dedicada a los que no saben nada de D3, pero si pican algo de Javascript, HTML y CSS. Comenzando por repasar lo básico de SVG, intentaremos aprender los componentes principales de D3 e incrementalmente construir una visualización sencilla. Al final de la charla vas a ser capaz de crear otras visualizaciones, ir al infinito y mas allá (mindblown)."
        speaker: miguelt
        level: cfp.level.basic

    ansible-vagrant-y-otras-yerbas:
        title: 'Ansible, Vagrant y otras yerbas.'
        description: 'Subir un nivel con el workflow de desarrollo. En esta charla veremos una introducción  a Vagrant y Ansible, enfocados a generar entornos de desarrollo multi-plataforma, regenerables e idénticos a producción. Además veremos como automatizar tareas cotidianas con Ansible, y como generar y distribuir nuestras propias vagrant boxes. De regalo: scripts para provisionar un LAMP con Ansible.'
        speaker: gastona
        level: null

    dentro-de-un-backend-esta-mi-aplicacion-funcionando:
        title: 'Dentro de un Backend ¿Esta mi aplicación funcionando?'
        description: >
          ¿Qué hay dentro de nuestros backends? Se presentarán partes fundamentales que todos deberíamos tener para tener un backend robusto en el que poder confiar. Veremos buenas prácticas para poder responder preguntas complejas en sistemas que generar muchas información: Métricas, Logs, Performance. Para razonar necesitamos datos, sólo con datos podemos obtener métricas la idea es abordar entre otras las siguientes preguntas: ¿Que preguntas deberían poder respondernos nuestras métricas? ¿Esta mi aplicación funcionando? Si no lo está, ¿que parte esta fallando? ¿Que áreas necesitan mejorar el rendimiento? ¿Necesito escalar? ¿Cual fue el impacto del último código deployado? ¿Ha repercutido sobre los usuarios? ¿Negativamente? ¿Deberiamos hacer rollback?
          Para ello se mostrará ejemplos utilizando e l stack ELTK: Elastisc Search / Logstash / Kibana https://www.elastic.co/products Veremos como manejar grandes volumenes de informacion relevante al funcionamiento de nuestra aplicación que puede estar distribuida en cientos de servidores, de una forma tolerante a fallas, robusta y escalable.
        speaker: sandinosaso
        level: cfp.level.advanced

    reload-no-seas-malo:
        title: 'reload? no seas malo!'
        description: "En esta charla hablare un poco sobre las diferencias de blocking io y non-blocking io. También veremos herramientas en php que nos permiten acercarnos al paradigma event driven programming como REACT y RATCHET php. Por ultimo veremos un poco sobre comunicación cliente - servidor utilizando WebSockets y php como backend!!!"
        speaker: capelan
        level: cfp.level.advanced

    from-mobile-to-web-app:
        title: 'Unicornios y navegadores, del mobile a la web.'
        description: >
         Vamos a ver como armar una aplicación que funcione offline, sea performante, tenga acceso a API's nativas del teléfono y no dependa de ningún app store para su distribución
        speaker: gabrielc
        level: cfp.level.advanced

    desarrollo-agil-de-software-scrum-y-xp:
        title: 'Desarrollo ágil de software: Scrum y XP'
        description: "Una introducción a la agilidad como una nueva visión del desarrollo de proyectos de software y de gestión en general, en especial en el método Scrum y las modernas prácticas técnicas de la Programación Extrema (XP) tales como, pair programming, TDD/BDD e integración continua entre otras."
        speaker: pablol
        level: cfp.level.basic

    redes-para-desarrolladores:
        title: 'Redes para Desarrolladores'
        description: "Hoy el mundo esta hyperconectado, no se conciben aplicaciones que no estén conectadas a una red, es su medio natural. Refrescar lo que pasa entre las aplicaciones y los servidores es el objetivo de esta charla."
        speaker: federicow
        level: cfp.level.basic

    proyecto-nahual:
        title: 'Testing como herramienta de inclusión social y laboral para nuestros jóvenes'
        description : "El objetivo de la presentación es compartir esta experiencia de casi un año en Uruguay y casi 10 en Argentina con 3 objetivos principales: 1) seguir acercando colaboradores que se involucren con la idea y permitan la apertura de más grupos, pudiendo llegar así a capacitar más jóvenes. 2) seguir difundiendo el emprendimiento para que las empresas se involucren y ofrezcan oportunidades a los egresados, ya sea a través de contrataciones o pasantías. 3) lograr el involucramiento de otras instituciones que quieran colaborar con infraestructura, materiales y/o recursos humanos como forma de continuar creciendo en cantidad y calidad de cursos."
        speaker: [gabrielm, rodrigog]
        level: cfp.level.basic

    aplicaciones-modernas-con-php:
        title: 'Aplicaciones modernas en PHP'
        description : "PHP ha cambiado mucho en estos años, también ha cambiado la forma en que desarrollamos / monitoreamos / deployamos etc. Te mostraremos cómo hacerlo con PHP usando las mejores prácticas y herramientas que PHP ofrece. Veremos composer, versionamiento, sistemas de deployment, estándares FIG, mejores prácticas, etc.. Luego de esta charla te irás con un pantallazo de cómo llevar tu aplicación y tu proceso de desarrollo al siguiente nivel."
        speaker: [iambrosi, av4tar, capelan]
        level: cfp.level.basic

    procesando-salesforce-outbound-messages-con-php-en-heroku:
        title: 'Procesando Salesforce Outbound Messages con PHP en Heroku'
        description : "Dentro de la plataforma de Salesforce, es muy común ver requerimientos de integración con sistemas externos. Con Outbound Messages, la plataforma permite enviar notificaciones de cambios (create o update) sobre los distintos objetos definidos en la metadata a diferentes aplicaciones externas. Estas notificaciones, significan implementar una interfase SOAP para poder procesarlas. En esta presentación, mostraremos como crear un Outbound Message en Salesforce y la respectiva aplicacion PHP que capture dichas notificaciones para su procesamiento en un sistema externo."
        speaker: aldof
        level: cfp.level.intermediate

    blog-de-noticias-tecnologicas:
        title: 'Blog de noticias tecnológicas'
        description : "Esta charla trata sobre una página web creada por mi estilo blog con temas relacionados al mundo tecnológico. La idea es poder transmitir los conocimientos que se aplicaron a dicha página web y como fue su construcción y su objetivo tocando los temas relacionados a: HTML, CSS, Javascript y MySQL."
        speaker: fabianl
        level: cfp.level.basic

    wordpress-much-mas-que-un-cms-para-blogs:
        title: 'Wordpress, mucho más que un CMS para Blogs'
        description : "Según w3techs.com, casi la cuarta parte de los sitios web en el mundo utilizan WordPress. Sus creadores algo bien deben haber hecho, no?\r\nHablaremos sobre que es Wordpress, cómo funciona su cola de funciones, el porqué de las variables globales y comentaremos a fondo dos de sus funciones más importantes: do_action() y apply_filters()."
        speaker: daniel
        level: cfp.level.intermediate

rooms:
    sala-1:
        room_name: 'Sala 1'
        title: cfp.level.basic
    sala-2:
        room_name: 'Sala 2'
        title: cfp.level.intermediate
    sala-3:
        room_name: 'Sala 3'
        title: cfp.level.advanced
    sala-4:
        room_name: 'Sala 4'
        title: cfp.level.advanced

schedules:
    '09:00 - 09:45': Registration
    '10:00 - 10:50':
        - { talk: deployando-con-rocketeer }
        - { talk: como-disenar-apis-restful-sin-morir-en-el-intento }
        - { talk: intro-a-d3-para-los-mas-chambones }
        - { talk: desarrollo-agil-de-software-scrum-y-xp }

    '11:00 - 11:50':
        - { talk: proyecto-nahual }
        - { talk: html5-jquery-php }
        - { talk: php-endemoniado-una-plataforma-de-mensajeria-sobre-php-y-mysql }
        - { talk: docker-from-the-basics-to-orquestration }

    '12:00 - 12:50':
        - { talk: implementando-una-arquitectura-de-microservicios }
        - { talk: procesando-salesforce-outbound-messages-con-php-en-heroku }
        - { talk: dentro-de-un-backend-esta-mi-aplicacion-funcionando }
        - { talk: intro-a-bdd }

    '13:00 - 13:50': Break
    '14:00 - 14:50':
        - { talk: introduccion-a-symfony-2 }
        - { talk: introduction-to-mongodb }
        - { talk: reload-no-seas-malo }
        - { talk: wordpress-much-mas-que-un-cms-para-blogs }

    '15:00 - 15:50':
        - { talk: yii-inicios }
        - { talk: blog-de-noticias-tecnologicas }
        - { talk: redes-para-desarrolladores }
        - { talk: drupal-que-es-y-que-hay-de-nuevo-en-la-version-8}

    '16:00 - 16:50':
        - { talk: laravel-en-plan-ceibal }
        - { talk: ansible-vagrant-y-otras-yerbas }
        - { talk: from-mobile-to-web-app }
        - { talk: aplicaciones-modernas-con-php}
